add gridengine retry, fix wrapperscript exit code check

diff --git a/src/geneflow/data/templates/wrapper-script.sh.j2 b/src/geneflow/data/templates/wrapper-script.sh.j2
--- a/src/geneflow/data/templates/wrapper-script.sh.j2
+++ b/src/geneflow/data/templates/wrapper-script.sh.j2
@@ -203,12 +203,13 @@ usage () {
 # report error code for command
 safeRunCommand() {
     cmd="$@"
-    eval "$cmd"
-    ERROR_CODE=$?
-    if [ ${ERROR_CODE} -ne 0 ]; then
-        echo "Error when executing command '${cmd}'"
-        exit ${ERROR_CODE}
-    fi
+    eval "$cmd; "'PIPESTAT=("${PIPESTATUS[@]}")'
+    for i in ${!PIPESTAT[@]}; do
+        if [ ${PIPESTAT[$i]} -ne 0 ]; then
+            echo "Error when executing command #${i}: '${cmd}'"
+            exit ${PIPESTAT[$i]}
+        fi
+    done
 }
 
 # print message and exit
